### ISSUE TITLE
bitcode issue with some library and solution.

### ISSUE THREAD

**Issue by ihomecall** [kwkhaw/SwiftAnyPic#2]
when I do pod install, and then compile, it always complains the bitcode not available for some of the library.

I found this solution. add this to the Podfile, it will disable bitcode for all library.

post_install do |installer|

  installer.pods_project.targets.each do |target|

```
target.build_configurations.each do |config|

  config.build_settings['ENABLE_BITCODE'] = 'NO'

end
```

  end

end

**Comment by kwkhaw** [comment]
@ihomecall Thanks, I will take a look into this. :-)

**Comment by kwkhaw** [comment]
@ihomecall I added it in this commit https://github.com/kwkhaw/SwiftAnyPic/commit/8be32effbe3730986606b8f9e7d21f7852f1a29b
Thanks!
