### ISSUE TITLE
How can I run this project? It's won't let me build

### ISSUE THREAD

**Issue by ghost** [kwkhaw/SwiftAnyPic#3]
Hi, when I try to run this project, its simulator is set to "IOS DEVICES" and not able to change the device to other types of simulators (iphone6, 5, 4, etc.).

**Comment by kwkhaw** [comment]
Hi @hongseung92 Which version of Xcode are you using?
Please try with Xcode 7 (not beta) and see if you still encounter the same issue.

**Comment by ghost** [comment]
@kwkhaw Thanks for the response :) I was wondering what the difference was between the PAPPhtoCell file and PAPPhotoHeaderView file. They have both classes that subclass PFTableViewCell but was wondering what the difference was. Thanks!!

**Comment by kwkhaw** [comment]
@hongseung92 your build is resolved? great!
Probably I'm not the right guy to explain the design.
But if you are asking what PAPPhotoCell and PAPPhotoHeaderView are, I can tell you how to find out. :-)
Launch the application in Xcode, then in PAPPhotoTimelineViewController.swift, put the break point at:
- around line 278: inside `photoHeaderView(:didTapUserButton:user)`
- around line 482: inside `didTapOnPhotoAction` (It will break when a PAPPhotoCell is tapped).
  They will break when you tap... the "photos". :-)
  Please let me know if it does not answer your question.
