### ISSUE TITLE
fatal error: unwrapping

### ISSUE THREAD

**Issue by ghost** [kwkhaw/SwiftAnyPic#4]
Hi,

I get the error:

fatal error: unexpectedly found nil while unwrapping an Optional value

in the below line.. any idea why? Thanks!

self.headerView = PAPPhotoDetailsHeaderView(frame: PAPPhotoDetailsHeaderView.rectForView(), photo:self.photo!)

**Comment by kwkhaw** [comment]
Hi @hongseung92 , thanks for reporting the issue.
Can you provide the following info?
- Xcode version
- Simulator or device? iPhone 5, 5s, 6 or 6s+?
- How to reproduce the issue?

Thanks!

**Comment by kwkhaw** [comment]
No further update from @hongseung92 . Closed.
